name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
        with:
          name: code
          path: .
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-new-step
        uses: actions/checkout@v2
      - run: ci/unit-test-app.sh
    needs: Clone-down
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Download
        run: chmod +x ci/build-app.sh && ci/build-app.sh
    needs: Clone-down
